version: "3.8"
services:
  dev-db:
    image: postgres:16
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - backend
networks:
  backend:
